export const DUMMY_PRODUCTS = [
  // Bed Category (8 items)
  {
    sales_board_id: 5,
    user_id: 1,
    title: "퀸사이즈 침대 프레임",
    content: "2년 사용, 깨끗한 상태입니다. 매트리스 미포함, 프레임만 판매합니다.",
    category: "bed",
    status: "판매중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 강남구",
    price: 300000,
    delivery_price: 80000,
    view_cnt: 25,
    like_cnt: 3,
    chat_cnt: 2,
    created_at: "2024-10-17T14:00:00",
    updated_at: "2024-10-17T14:00:00",
    isSell: "N",
    imageUrl: ["/images/bed2.png", "/images/bed3.png"],
    isLiked: false
  },
  {
    sales_board_id: 6,
    user_id: 2,
    title: "싱글 침대 매트리스",
    content: "호텔용 매트리스, 거의 새것입니다. 6개월 사용, 케이스 포함.",
    category: "bed",
    status: "예약중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 서초구",
    price: 150000,
    delivery_price: 50000,
    view_cnt: 42,
    like_cnt: 7,
    chat_cnt: 4,
    created_at: "2024-10-16T11:00:00",
    updated_at: "2024-10-16T11:00:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 7,
    user_id: 3,
    title: "원목 침대 프레임",
    content: "고급 원목 사용, 침실 분위기 UP. 퀸사이즈, 특별한 하자 없음.",
    category: "bed",
    status: "판매중",
    trade_method: "직거래,택배",
    isSafe: true,
    hope_location: "서울시 송파구",
    price: 450000,
    delivery_price: 100000,
    view_cnt: 15,
    like_cnt: 2,
    chat_cnt: 1,
    created_at: "2024-10-15T09:30:00",
    updated_at: "2024-10-15T09:30:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 8,
    user_id: 4,
    title: "킹사이즈 침대세트",
    content: "매트리스, 프레임 풀세트. 이사로 인한 급처분, 실사용 1년.",
    category: "bed",
    status: "판매완료",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 강동구",
    price: 800000,
    delivery_price: 150000,
    view_cnt: 98,
    like_cnt: 15,
    chat_cnt: 7,
    created_at: "2024-10-14T17:20:00",
    updated_at: "2024-10-14T17:20:00",
    isSell: "Y",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 9,
    user_id: 5,
    title: "수납형 싱글침대",
    content: "서랍장 포함, 공간활용도 높음. 매트리스 별도 구매 가능.",
    category: "bed",
    status: "판매중",
    trade_method: "택배",
    isSafe: false,
    hope_location: "서울시 노원구",
    price: 250000,
    delivery_price: 60000,
    view_cnt: 33,
    like_cnt: 5,
    chat_cnt: 3,
    created_at: "2024-10-13T13:15:00",
    updated_at: "2024-10-13T13:15:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 10,
    user_id: 6,
    title: "아기 침대",
    content: "원목 유아용 침대, 가드레일 포함. 안전인증 완료 제품.",
    category: "bed",
    status: "예약중",
    trade_method: "직거래,택배",
    isSafe: true,
    hope_location: "서울시 광진구",
    price: 120000,
    delivery_price: 30000,
    view_cnt: 67,
    like_cnt: 12,
    chat_cnt: 5,
    created_at: "2024-10-12T10:40:00",
    updated_at: "2024-10-12T10:40:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 11,
    user_id: 7,
    title: "접이식 침대",
    content: "1인용 간이침대, 손님용으로 추천. 보관가방 포함.",
    category: "bed",
    status: "판매중",
    trade_method: "택배",
    isSafe: false,
    hope_location: "서울시 성북구",
    price: 50000,
    delivery_price: 8000,
    view_cnt: 41,
    like_cnt: 6,
    chat_cnt: 2,
    created_at: "2024-10-11T16:50:00",
    updated_at: "2024-10-11T16:50:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 12,
    user_id: 8,
    title: "전동 리클라이닝 침대",
    content: "전동 조절 가능, 리모컨 포함. 실버케어용 추천.",
    category: "bed",
    status: "판매중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 용산구",
    price: 1200000,
    delivery_price: 200000,
    view_cnt: 22,
    like_cnt: 4,
    chat_cnt: 3,
    created_at: "2024-10-10T09:30:00",
    updated_at: "2024-10-10T09:30:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },

  // Desk Category (8 items)
  {
    sales_board_id: 13,
    user_id: 2,
    title: "게이밍 컴퓨터 책상",
    content: "LED 장착, 케이블 홀더 포함. 듀얼모니터 설치 가능.",
    category: "desk",
    status: "판매중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 동작구",
    price: 180000,
    delivery_price: 40000,
    view_cnt: 65,
    like_cnt: 8,
    chat_cnt: 3,
    created_at: "2024-10-14T16:20:00",
    updated_at: "2024-10-14T16:20:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 14,
    user_id: 3,
    title: "원목 좌식 책상",
    content: "참나무 원목, 높이 조절 가능. 전통 스타일.",
    category: "desk",
    status: "예약중",
    trade_method: "택배",
    isSafe: false,
    hope_location: "서울시 종로구",
    price: 90000,
    delivery_price: 15000,
    view_cnt: 38,
    like_cnt: 5,
    chat_cnt: 2,
    created_at: "2024-10-09T14:25:00",
    updated_at: "2024-10-09T14:25:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 15,
    user_id: 4,
    title: "접이식 노트북 책상",
    content: "이동식, 높이/각도 조절 가능. 소파/침대에서 사용 가능.",
    category: "desk",
    status: "판매중",
    trade_method: "택배",
    isSafe: true,
    hope_location: "서울시 강서구",
    price: 45000,
    delivery_price: 5000,
    view_cnt: 72,
    like_cnt: 9,
    chat_cnt: 4,
    created_at: "2024-10-08T11:30:00",
    updated_at: "2024-10-08T11:30:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 16,
    user_id: 5,
    title: "스탠딩 데스크",
    content: "전동식 높이 조절, 프리셋 3단계. 케이블 정리함 포함.",
    category: "desk",
    status: "판매중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 마포구",
    price: 350000,
    delivery_price: 50000,
    view_cnt: 89,
    like_cnt: 14,
    chat_cnt: 6,
    created_at: "2024-10-07T15:45:00",
    updated_at: "2024-10-07T15:45:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 17,
    user_id: 6,
    title: "화장대 겸용 책상",
    content: "거울 포함, 수납공간 많음. 화이트 컬러.",
    category: "desk",
    status: "판매완료",
    trade_method: "직거래,택배",
    isSafe: true,
    hope_location: "서울시 서대문구",
    price: 120000,
    delivery_price: 30000,
    view_cnt: 95,
    like_cnt: 11,
    chat_cnt: 5,
    created_at: "2024-10-06T13:10:00",
    updated_at: "2024-10-06T13:10:00",
    isSell: "Y",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
  {
    sales_board_id: 18,
    user_id: 7,
    title: "책상 + 책장 세트",
    content: "일체형 책상/책장 세트. 학생용으로 적합.",
    category: "desk",
    status: "판매중",
    trade_method: "직거래",
    isSafe: false,
    hope_location: "서울시 영등포구",
    price: 200000,
    delivery_price: 60000,
    view_cnt: 43,
    like_cnt: 6,
    chat_cnt: 2,
    created_at: "2024-10-05T17:30:00",
    updated_at: "2024-10-05T17:30:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: false
  },
  {
    sales_board_id: 19,
    user_id: 8,
    title: "2인용 책상",
    content: "나란히 앉는 구조, 파티션 포함. 재택근무용 추천.",
    category: "desk",
    status: "예약중",
    trade_method: "직거래",
    isSafe: true,
    hope_location: "서울시 동대문구",
    price: 250000,
    delivery_price: 70000,
    view_cnt: 56,
    like_cnt: 8,
    chat_cnt: 4,
    created_at: "2024-10-04T09:15:00",
    updated_at: "2024-10-04T09:15:00",
    isSell: "N",
    imageUrl: ["/images/bed3.png", "/images/bed2.png"],
    isLiked: true
  },
]