import localFont from "next/font/local";
import "./globals.css";
import ClientComponent from './components/ClientComponent';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <div className="grid-container max-w-screen-xl mx-auto min-h-screen">
          {/* <div className="content-area bg-white py-10 shadow-md"> */}
          <div className="content-area bg-white shadow-md">
            <ClientComponent>
              {children}
            </ClientComponent>
          </div>
        </div>
      </body>
    </html>
  );
}
