server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: homeggu-gateway
  cloud:
    gateway:
      #      default-filters:
      #        - name: GlobalFilter
      #          args:
      #            baseMessage: Spring Cloud Gateway GlobalFilter
      #            preLogger: true
      #            postLogger: true
      routes:
        - id: homeggu-pay
          uri: lb://HOMEGGU-PAY
          predicates:
            - Path=/pay/**
          filters:
            #            - AddRequestHeader=first-request, first-request-header
            #            - AddResponseHeader=first-response, first-response-header
            #            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true
        - id: homeggu-goods
          uri: lb://HOMEGGU-GOODS
          predicates:
            - Path=/goods/**
        - id: homeggu-chat
          uri: lb://HOMEGGU-CHAT
          predicates:
            - Path=/chat/**
        - id: homeggu-user
          uri: lb://HOMEGGU-USER
          predicates:
            - Path=/user/**