server:
  port: 8084
  servlet:
    context-path: /

spring:
  application:
    name: homeggu-user

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: ssafy
  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 10

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

